<a href="https://colab.research.google.com/github/yashrajmodani/Data-Analaysis/blob/main/Day3_DataFrame.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
np.random.seed(101)
mydata = np.random.randint(0,101,(4,3))
print(mydata)    #Just a numy array

[[95 11 81]
 [70 63 87]
 [75  9 77]
 [40  4 63]]

In [ ]:
myindex = ['CA','NY','Az',"TX"]
mycols = ['Jan','Feb','Mar']

In [ ]:
df = pd.DataFrame(data = mydata)
print(df)  # only numeric index

    0   1   2
0  95  11  81
1  70  63  87
2  75   9  77
3  40   4  63

In [ ]:
df = pd.DataFrame(data = mydata, index = myindex)
print(df)   #Labeled Index

     0   1   2
CA  95  11  81
NY  70  63  87
Az  75   9  77
TX  40   4  63

In [ ]:
df = pd.DataFrame(data = mydata,index = myindex,columns=mycols)
print(df)    #Label Index with columns

    Jan  Feb  Mar
CA   95   11   81
NY   70   63   87
Az   75    9   77
TX   40    4   63

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, CA to TX
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Jan     4 non-null      int64
 1   Feb     4 non-null      int64
 2   Mar     4 non-null      int64
dtypes: int64(3)
memory usage: 300.0+ bytes

New CSV

In [ ]:
# Create a dataframe CSV File

df= pd.read_csv("/content/tips.csv")

In [ ]:
df

,total_bill,tip,gender,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3.560330e+15,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4.478070e+15,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6.011810e+15,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4.676140e+15,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4.832730e+15,Sun2251
...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5.296070e+15,Sat2657
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3.506810e+15,Sat1766
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6.011890e+15,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4.375220e+12,Sat17
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3.511450e+15,Thur672

In [ ]:
df.columns # Columns name

Index(['total_bill', 'tip', 'gender', 'smoker', 'day', 'time', 'size',
       'price_per_person', 'Payer Name', 'CC Number', 'Payment ID'],
      dtype='object')

In [ ]:
df.index # Index

RangeIndex(start=0, stop=244, step=1)

In [ ]:
df.head(3) #First Three row

,total_bill,tip,gender,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3.560330e+15,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4.478070e+15,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6.011810e+15,Sun4458

In [ ]:
df.tail(3) # Last 3 rows

,total_bill,tip,gender,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6.011890e+15,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4.375220e+12,Sat17
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3.511450e+15,Thur672

In [ ]:
df.info()  #Information about df, including datatypes and memory used

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   total_bill        244 non-null    float64
 1   tip               244 non-null    float64
 2   gender            244 non-null    object
 3   smoker            244 non-null    object
 4   day               244 non-null    object
 5   time              244 non-null    object
 6   size              244 non-null    int64
 7   price_per_person  244 non-null    float64
 8   Payer Name        244 non-null    object
 9   CC Number         244 non-null    float64
 10  Payment ID        244 non-null    object
dtypes: float64(4), int64(1), object(6)
memory usage: 21.1+ KB

In [ ]:
len(df) #No. of rows

244

In [ ]:
df.describe()  #Statistical Summary

       total_bill         tip        size  price_per_person     CC Number
count  244.000000  244.000000  244.000000        244.000000  2.440000e+02
mean    19.785943    2.998279    2.569672          7.888197  2.563495e+15
std      8.902412    1.383638    0.951100          2.914234  2.369340e+15
min      3.070000    1.000000    1.000000          2.880000  6.040679e+10
25%     13.347500    2.000000    2.000000          5.800000  3.040732e+13
50%     17.795000    2.900000    2.000000          7.255000  3.525320e+15
75%     24.127500    3.562500    3.000000          9.390000  4.553675e+15
max     50.810000   10.000000    6.000000         20.270000  6.596450e+15

In [ ]:
df.describe().transpose()  # Statistical Summary , Better Organized

,count,mean,std,min,25%,50%,75%,max
total_bill,244.0,1.978594e+01,8.902412e+00,3.070000e+00,1.334750e+01,1.779500e+01,2.412750e+01,5.081000e+01
tip,244.0,2.998279e+00,1.383638e+00,1.000000e+00,2.000000e+00,2.900000e+00,3.562500e+00,1.000000e+01
size,244.0,2.569672e+00,9.510998e-01,1.000000e+00,2.000000e+00,2.000000e+00,3.000000e+00,6.000000e+00
price_per_person,244.0,7.888197e+00,2.914234e+00,2.880000e+00,5.800000e+00,7.255000e+00,9.390000e+00,2.027000e+01
CC Number,244.0,2.563495e+15,2.369340e+15,6.040679e+10,3.040732e+13,3.525320e+15,4.553675e+15,6.596450e+15

In [ ]:
# Select a Single columns

print(df['total_bill'])
print(df.total_bill)
print(type(df(['total_bill'])))

In [ ]:
# Select multiple columns
# Note how its a python list of columns names ! Thus the double brackets.
df[["total_bill",'tip']]

     total_bill   tip
0         16.99  1.01
1         10.34  1.66
2         21.01  3.50
3         23.68  3.31
4         24.59  3.61
..          ...   ...
239       29.03  5.92
240       27.18  2.00
241       22.67  2.00
242       17.82  1.75
243       18.78  3.00

[244 rows x 2 columns]

In [ ]:
#Create a new column

df['tip_percentage'] = 100 * df['tip'] / df['total_bill']
df.head()

,total_bill,tip,gender,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,tip_percentage
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3.560330e+15,Sun2959,5.944673
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4.478070e+15,Sun4608,16.054159
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6.011810e+15,Sun4458,16.658734
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4.676140e+15,Sun5260,13.978041
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4.832730e+15,Sun2251,14.680765

In [ ]:
df['price_per_person'] =df['total_bill'] / df['size']
df.head()

,total_bill,tip,gender,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,tip_percentage
0,16.99,1.01,Female,No,Sun,Dinner,2,8.495000,Christy Cunningham,3.560330e+15,Sun2959,5.944673
1,10.34,1.66,Male,No,Sun,Dinner,3,3.446667,Douglas Tucker,4.478070e+15,Sun4608,16.054159
2,21.01,3.50,Male,No,Sun,Dinner,3,7.003333,Travis Walters,6.011810e+15,Sun4458,16.658734
3,23.68,3.31,Male,No,Sun,Dinner,2,11.840000,Nathaniel Harris,4.676140e+15,Sun5260,13.978041
4,24.59,3.61,Female,No,Sun,Dinner,4,6.147500,Tonya Carter,4.832730e+15,Sun2251,14.680765

In [ ]:
#Adjust Existing col

df['price_per_person'] =np.round(df['total_bill'] / df['size'],2)
df.head()

,total_bill,tip,gender,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,tip_percentage
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3.560330e+15,Sun2959,5.944673
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4.478070e+15,Sun4608,16.054159
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6.011810e+15,Sun4458,16.658734
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4.676140e+15,Sun5260,13.978041
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4.832730e+15,Sun2251,14.680765

In [ ]:
#Remove Columns

df = df.drop("tip_percentage",axis = 1)
df.head()

,total_bill,tip,gender,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3.560330e+15,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4.478070e+15,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6.011810e+15,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4.676140e+15,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4.832730e+15,Sun2251

In [ ]:
# Index
df.index

RangeIndex(start=0, stop=244, step=1)

In [ ]:
df = df.set_index("Payment ID")
df.head()

,total_bill,tip,gender,smoker,day,time,size,price_per_person,Payer Name,CC Number
Payment ID,,,,,,,,,,
Sun2959,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3.560330e+15
Sun4608,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4.478070e+15
Sun4458,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6.011810e+15
Sun5260,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4.676140e+15
Sun2251,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4.832730e+15

In [ ]:
df = df.reset_index()   #set it to a default integer value
df.head()

,Payment ID,total_bill,tip,gender,smoker,day,time,size,price_per_person,Payer Name,CC Number
0,Sun2959,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3.560330e+15
1,Sun4608,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4.478070e+15
2,Sun4458,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6.011810e+15
3,Sun5260,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4.676140e+15
4,Sun2251,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4.832730e+15

# **Air Bnb Dataset**

In [ ]:
#another index example - air BNB dataset from kaggle
#default index

df_airbnb = pd.read_csv("AB_NYC_2019.csv")
df_airbnb.head(3)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,2018-10-19,0.21,6,365
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,2019-05-21,0.38,2,355
2,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,NaN,NaN,1,365

In [ ]:
#Make id column the index
df2 = df_airbnb.set_index("id")
df2.head(3)
df2.name[3647] #Get the name for id 3647

'THE VILLAGE OF HARLEM....NEW YORK !'

In [ ]:
#set pandas display options to show all columns
numeric_columns = df2.select_dtypes(include = ['float64','int64'])

#Include 'room_type' column in numeric_column DataFrame
numeric_columns['room_type'] = df2['room_type']
df3 = numeric_columns.groupby('room_type').mean()
pd.set_option('display.max_columns',None)
df3.head(3)

,host_id,latitude,longitude,price,minimum_nights,number_of_reviews,reviews_per_month,calculated_host_listings_count,availability_365
room_type,,,,,,,,,
Entire home/apt,6.175593e+07,40.728649,-73.960696,211.794246,8.506907,22.842418,1.306578,10.698335,111.920304
Private room,7.247514e+07,40.729208,-73.942924,89.780973,5.377900,24.112962,1.445209,3.227717,111.203933
Shared room,1.026241e+08,40.730514,-73.943343,70.127586,6.475000,16.600000,1.471726,4.662931,162.000862

In [ ]:
df3.index

Index(['Entire home/apt', 'Private room', 'Shared room'], dtype='object', name='room_type')

In [ ]:
#Note that room_type has become an index - we can again convert it into a normal column
df3 = df3.reset_index()
pd.reset_option('display.max_columns') #Also reset the column display to default
df3

,index,room_type,host_id,latitude,longitude,price,minimum_nights,number_of_reviews,reviews_per_month,calculated_host_listings_count,availability_365
0,0,Entire home/apt,6.175593e+07,40.728649,-73.960696,211.794246,8.506907,22.842418,1.306578,10.698335,111.920304
1,1,Private room,7.247514e+07,40.729208,-73.942924,89.780973,5.377900,24.112962,1.445209,3.227717,111.203933
2,2,Shared room,1.026241e+08,40.730514,-73.943343,70.127586,6.475000,16.600000,1.471726,4.662931,162.000862

In [ ]:
#Rows
#Get a single row
#Integer based
df3.iloc[0]

host_id                           6.175593e+07
latitude                          4.072865e+01
longitude                        -7.396070e+01
price                             2.117942e+02
minimum_nights                    8.506907e+00
number_of_reviews                 2.284242e+01
reviews_per_month                 1.306578e+00
calculated_host_listings_count    1.069834e+01
availability_365                  1.119203e+02
Name: Entire home/apt, dtype: float64

In [ ]:
#Name based
#First set the index to the column which will be used in locating  the row

df = df_airbnb.set_index('host_name')
df.loc['John']

,id,name,host_id,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
host_name,,,,,,,,,,,,,,,
John,2539,Clean & quiet apt home by the park,2787,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,2018-10-19,0.21,6,365
John,148201,NYC - Sunny Greenwich Village 1br,715807,Manhattan,Greenwich Village,40.72831,-74.00177,Entire home/apt,175,3,18,2013-05-31,0.19,1,0
John,234870,Private Room With GREAT Location,1229984,Queens,Long Island City,40.74581,-73.95295,Private room,75,30,65,2017-07-31,0.74,3,219
John,400039,Big Beautiful Railroad in Brooklyn,1488809,Brooklyn,Bushwick,40.70339,-73.92945,Entire home/apt,130,30,53,2017-06-30,0.68,1,0
John,484297,Large home in most desirable Brooklyn hood!,2397411,Brooklyn,Clinton Hill,40.68545,-73.96534,Entire home/apt,350,4,10,2018-09-12,0.12,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
John,35836317,Gorgeous Duplex 2BED/1.5BA Modern,269242923,Manhattan,Kips Bay,40.74490,-73.97888,Entire home/apt,288,5,2,2019-06-30,2.00,1,74
John,35871036,Huge 1 bedroom w/ a backyard near the heart of...,226414996,Queens,Ditmars Steinway,40.77170,-73.90799,Entire home/apt,90,3,0,NaN,NaN,2,21
John,35984474,Perfect Weekend Stay,229739739,Brooklyn,Flatbush,40.64726,-73.95455,Private room,85,14,0,NaN,NaN,2,176
John,36140542,Wonderful Summer Vacation Getaways For Weeken...,229739739,Brooklyn,Flatbush,40.64600,-73.95455,Private room,85,7,0,NaN,NaN,2,176
John,36391615,Hidden gem! Cozy home in heart of Lower East Side,70653354,Manhattan,Lower East Side,40.72013,-73.98769,Entire home/apt,235,1,0,NaN,NaN,1,349

In [ ]:
#Remove a row
df = df.drop('John',axis = 0)
df.head()

,id,name,host_id,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
host_name,,,,,,,,,,,,,,,
Jennifer,2595,Skylit Midtown Castle,2845,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,2019-05-21,0.38,2,355
Elisabeth,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,NaN,NaN,1,365
LisaRoxanne,3831,Cozy Entire Floor of Brownstone,4869,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,2019-07-05,4.64,1,194
Laura,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80,10,9,2018-11-19,0.10,1,0
Chris,5099,Large Cozy 1 BR Apartment In Midtown East,7322,Manhattan,Murray Hill,40.74767,-73.97500,Entire home/apt,200,3,74,2019-06-22,0.59,1,129

# ***Tips Dataset***

In [ ]:
df = pd.read_csv("tips.csv")
df.head()

,total_bill,tip,gender,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3.560330e+15,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4.478070e+15,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6.011810e+15,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4.676140e+15,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4.832730e+15,Sun2251

In [ ]:
#Conditions
df['total_bill'] < 30 #True/False

0      True
1      True
2      True
3      True
4      True
       ...
239    True
240    True
241    True
242    True
243    True
Name: total_bill, Length: 244, dtype: bool

In [ ]:
bool_series = df['total_bill'] > 30  #save in variable
bool_series #True/False

0      False
1      False
2      False
3      False
4      False
       ...
239    False
240    False
241    False
242    False
243    False
Name: total_bill, Length: 244, dtype: bool

In [ ]:
df[bool_series].head() #Actual results, applying the true/ flase conditions

,total_bill,tip,gender,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
11,35.26,5.00,Female,No,Sun,Dinner,4,8.82,Diane Macias,4.577820e+15,Sun6686
23,39.42,7.58,Male,No,Sat,Dinner,4,9.86,Lance Peterson,3.542580e+15,Sat239
39,31.27,5.00,Male,No,Sat,Dinner,3,10.42,Mr. Brandon Berry,6.011530e+15,Sat6373
44,30.40,5.60,Male,No,Sun,Dinner,4,7.60,Todd Cooper,5.038470e+11,Sun2274
47,32.40,6.00,Male,No,Sun,Dinner,4,8.10,James Barnes,3.552000e+15,Sun9677

In [ ]:
df[df['total_bill'] > 30].head()

,total_bill,tip,gender,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
11,35.26,5.00,Female,No,Sun,Dinner,4,8.82,Diane Macias,4.577820e+15,Sun6686
23,39.42,7.58,Male,No,Sat,Dinner,4,9.86,Lance Peterson,3.542580e+15,Sat239
39,31.27,5.00,Male,No,Sat,Dinner,3,10.42,Mr. Brandon Berry,6.011530e+15,Sat6373
44,30.40,5.60,Male,No,Sun,Dinner,4,7.60,Todd Cooper,5.038470e+11,Sun2274
47,32.40,6.00,Male,No,Sun,Dinner,4,8.10,James Barnes,3.552000e+15,Sun9677

In [ ]:
#Another syntax
df.total_bill > 30

0      False
1      False
2      False
3      False
4      False
       ...
239    False
240    False
241    False
242    False
243    False
Name: total_bill, Length: 244, dtype: bool

In [ ]:
df[df.total_bill > 30].head()

,total_bill,tip,gender,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
11,35.26,5.00,Female,No,Sun,Dinner,4,8.82,Diane Macias,4.577820e+15,Sun6686
23,39.42,7.58,Male,No,Sat,Dinner,4,9.86,Lance Peterson,3.542580e+15,Sat239
39,31.27,5.00,Male,No,Sat,Dinner,3,10.42,Mr. Brandon Berry,6.011530e+15,Sat6373
44,30.40,5.60,Male,No,Sun,Dinner,4,7.60,Todd Cooper,5.038470e+11,Sun2274
47,32.40,6.00,Male,No,Sun,Dinner,4,8.10,James Barnes,3.552000e+15,Sun9677

In [ ]:
df[df['gender'] == 'Male'].head()

,total_bill,tip,gender,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4.478070e+15,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6.011810e+15,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4.676140e+15,Sun5260
5,25.29,4.71,Male,No,Sun,Dinner,4,6.32,Erik Smith,2.131400e+14,Sun9679
6,8.77,2.00,Male,No,Sun,Dinner,2,4.38,Kristopher Johnson,2.223730e+15,Sun5985

In [ ]:
#Multiple conditions
df_new = df[(df['total_bill'] > 30) & (df['gender'] == 'Male')]
df_new.head()

,total_bill,tip,gender,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
23,39.42,7.58,Male,No,Sat,Dinner,4,9.86,Lance Peterson,3.542580e+15,Sat239
39,31.27,5.00,Male,No,Sat,Dinner,3,10.42,Mr. Brandon Berry,6.011530e+15,Sat6373
44,30.40,5.60,Male,No,Sun,Dinner,4,7.60,Todd Cooper,5.038470e+11,Sun2274
47,32.40,6.00,Male,No,Sun,Dinner,4,8.10,James Barnes,3.552000e+15,Sun9677
56,38.01,3.00,Male,Yes,Sat,Dinner,4,9.50,James Christensen DDS,3.497940e+14,Sat8903

In [ ]:
df_new = df[(df['total_bill'] > 30) & ~(df['gender'] == 'Male')]
df_new.head()

,total_bill,tip,gender,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
11,35.26,5.00,Female,No,Sun,Dinner,4,8.82,Diane Macias,4.577820e+15,Sun6686
52,34.81,5.20,Female,No,Sun,Dinner,4,8.70,Emily Daniel,4.291280e+15,Sun6165
85,34.83,5.17,Female,No,Thur,Lunch,4,8.71,Shawna Cook,6.011790e+15,Thur7972
102,44.30,2.50,Female,Yes,Sat,Dinner,3,14.77,Heather Cohen,3.797710e+14,Sat6240
197,43.11,5.00,Female,Yes,Thur,Lunch,4,10.78,Brooke Soto,5.544900e+15,Thur9313

In [ ]:
df_new = df[(df['total_bill'] > 30) & (df['gender'] != 'Male')]
df_new.head()

,total_bill,tip,gender,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
11,35.26,5.00,Female,No,Sun,Dinner,4,8.82,Diane Macias,4.577820e+15,Sun6686
52,34.81,5.20,Female,No,Sun,Dinner,4,8.70,Emily Daniel,4.291280e+15,Sun6165
85,34.83,5.17,Female,No,Thur,Lunch,4,8.71,Shawna Cook,6.011790e+15,Thur7972
102,44.30,2.50,Female,Yes,Sat,Dinner,3,14.77,Heather Cohen,3.797710e+14,Sat6240
197,43.11,5.00,Female,Yes,Thur,Lunch,4,10.78,Brooke Soto,5.544900e+15,Thur9313

In [ ]:
df_new = df[(df['total_bill'] > 30) & (df['tip'] > 5)]
df_new.head()

,total_bill,tip,gender,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
23,39.42,7.58,Male,No,Sat,Dinner,4,9.86,Lance Peterson,3.542580e+15,Sat239
44,30.40,5.60,Male,No,Sun,Dinner,4,7.60,Todd Cooper,5.038470e+11,Sun2274
47,32.40,6.00,Male,No,Sun,Dinner,4,8.10,James Barnes,3.552000e+15,Sun9677
52,34.81,5.20,Female,No,Sun,Dinner,4,8.70,Emily Daniel,4.291280e+15,Sun6165
59,48.27,6.73,Male,No,Sat,Dinner,4,12.07,Brian Ortiz,6.596450e+15,Sat8139

In [ ]:
#Conditional is in operatior
options = ['Sat','Sun']
df[df['day'].isin(options)].head()

,total_bill,tip,gender,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3.560330e+15,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4.478070e+15,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6.011810e+15,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4.676140e+15,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4.832730e+15,Sun2251

In [ ]:
#sort_values
df.sort_values("tip")

,total_bill,tip,gender,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
67,3.07,1.00,Female,Yes,Sat,Dinner,1,3.07,Tiffany Brock,4.359490e+15,Sat3455
236,12.60,1.00,Male,Yes,Sat,Dinner,2,6.30,Matthew Myers,3.543680e+15,Sat5032
92,5.75,1.00,Female,Yes,Fri,Dinner,2,2.88,Leah Ramirez,3.508910e+15,Fri3780
111,7.25,1.00,Female,No,Sat,Dinner,1,7.25,Terri Jones,3.559220e+15,Sat4801
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3.560330e+15,Sun2959
...,...,...,...,...,...,...,...,...,...,...,...
141,34.30,6.70,Male,No,Thur,Lunch,6,5.72,Steven Carlson,3.526520e+15,Thur1025
59,48.27,6.73,Male,No,Sat,Dinner,4,12.07,Brian Ortiz,6.596450e+15,Sat8139
23,39.42,7.58,Male,No,Sat,Dinner,4,9.86,Lance Peterson,3.542580e+15,Sat239
212,48.33,9.00,Male,No,Sat,Dinner,4,12.08,Alex Williamson,6.762190e+11,Sat4590
170,50.81,10.00,Male,Yes,Sat,Dinner,3,16.94,Gregory Clark,5.473850e+15,Sat1954

In [ ]:
#correlation
df[['total_bill','tip']].corr()

            total_bill       tip
total_bill    1.000000  0.675734
tip           0.675734  1.000000

In [ ]:
# idxmin and idxmax
df['total_bill'].max()

50.81

In [ ]:
df['total_bill'].idxmax()

170

In [ ]:
df['total_bill'].idxmin()

67

In [ ]:
print(df.iloc[67])
print(df.iloc[170])

total_bill                        3.07
tip                                1.0
gender                          Female
smoker                             Yes
day                                Sat
time                            Dinner
size                                 1
price_per_person                  3.07
Payer Name               Tiffany Brock
CC Number           4359490000000000.0
Payment ID                     Sat3455
Name: 67, dtype: object
total_bill                       50.81
tip                               10.0
gender                            Male
smoker                             Yes
day                                Sat
time                            Dinner
size                                 3
price_per_person                 16.94
Payer Name               Gregory Clark
CC Number           5473850000000000.0
Payment ID                     Sat1954
Name: 170, dtype: object

In [ ]:
#Value_counts - get count on categorical columns
print(df['smoker'].value_counts())  #Smoker and non-smoker
print(df['gender'].value_counts())

smoker
No     151
Yes     93
Name: count, dtype: int64
gender
Male      157
Female     87
Name: count, dtype: int64

In [ ]:
#unique

print(df['size'].unique()) # all the unique values as an array
print(df['size'].nunique())  # Number of unique values i.e count of above array
print(df['time'].unique())   #For a char column

[2 3 4 1 6 5]
6
['Dinner' 'Lunch']

In [ ]:
#between : option for inclusive for both,left,right, niether

df['total_bill'].between(10,20,inclusive = 'both')  #True/False

0       True
1       True
2      False
3      False
4      False
       ...
239    False
240    False
241    False
242     True
243     True
Name: total_bill, Length: 244, dtype: bool

In [ ]:
df[df['total_bill'].between(10,20,inclusive = 'both')]  #Actual results

,total_bill,tip,gender,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3.560330e+15,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4.478070e+15,Sun4608
8,15.04,1.96,Male,No,Sun,Dinner,2,7.52,Joseph Mcdonald,3.522870e+15,Sun6820
9,14.78,3.23,Male,No,Sun,Dinner,2,7.39,Jerome Abbott,3.532120e+15,Sun3775
10,10.27,1.71,Male,No,Sun,Dinner,2,5.14,William Riley,5.662880e+11,Sun2546
...,...,...,...,...,...,...,...,...,...,...,...
234,15.53,3.00,Male,Yes,Sat,Dinner,2,7.76,Tracy Douglas,4.097940e+15,Sat7220
235,10.07,1.25,Male,No,Sat,Dinner,2,5.04,Sean Gonzalez,3.534020e+15,Sat4615
236,12.60,1.00,Male,Yes,Sat,Dinner,2,6.30,Matthew Myers,3.543680e+15,Sat5032
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4.375220e+12,Sat17
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3.511450e+15,Thur672

In [ ]:
#sample data, randomly selected
df.sample(5)    # 5 rows

,total_bill,tip,gender,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4.676140e+15,Sun5260
32,15.06,3.00,Female,No,Sat,Dinner,2,7.53,Amanda Wilson,2.131860e+14,Sat1327
177,14.48,2.00,Male,Yes,Sun,Dinner,2,7.24,John Dudley,4.565180e+15,Sun6203
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4.375220e+12,Sat17
77,27.20,4.00,Male,No,Thur,Lunch,4,6.80,John Davis,3.034480e+13,Thur4924

In [ ]:
df.sample(frac = 0.1) #10% of rows

,total_bill,tip,gender,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
85,34.83,5.17,Female,No,Thur,Lunch,4,8.71,Shawna Cook,6.011790e+15,Thur7972
56,38.01,3.00,Male,Yes,Sat,Dinner,4,9.50,James Christensen DDS,3.497940e+14,Sat8903
129,22.82,2.18,Male,No,Thur,Lunch,3,7.61,Raymond Torres,4.855780e+12,Thur9424
125,29.80,4.20,Female,No,Thur,Lunch,6,4.97,Angela Sanchez,5.038570e+11,Thur3948
89,21.16,3.00,Male,No,Thur,Lunch,2,10.58,Keith Lewis,4.356010e+15,Thur6273
142,41.19,5.00,Male,No,Thur,Lunch,5,8.24,Eric Andrews,4.356530e+15,Thur3621
51,10.29,2.60,Female,No,Sun,Dinner,2,5.14,Jessica Ibarra,4.999760e+12,Sun4474
157,25.00,3.75,Female,No,Sun,Dinner,4,6.25,Laura Robles,2.131590e+14,Sun7015
151,13.13,2.00,Male,No,Sun,Dinner,2,6.56,Jason Arnold,3.571830e+15,Sun2127
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6.011890e+15,Sat3880
43,9.68,1.32,Male,No,Sun,Dinner,2,4.84,Christopher Spears,4.387670e+15,Sun3279
42,13.94,3.06,Male,No,Sun,Dinner,2,6.97,Bryan Brown,3.623120e+13,Sun1699
220,12.16,2.20,Male,Yes,Fri,Lunch,2,6.08,Ricky Johnson,2.131100e+14,Fri4607
145,8.35,1.50,Female,No,Thur,Lunch,2,4.18,Amy Young,4.285450e+12,Thur9331
31,18.35,2.50,Male,No,Sat,Dinner,4,4.59,Danny Santiago,6.304160e+11,Sat4947
134,18.26,3.25,Female,No,Thur,Lunch,2,9.13,Karen Rodriguez,4.952600e+12,Thur75
78,22.76,3.00,Male,No,Thur,Lunch,2,11.38,Chris Hahn,3.591890e+15,Thur2863
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3.506810e+15,Sat1766
158,13.39,2.61,Female,No,Sun,Dinner,2,6.70,Ashley Boyd,3.571090e+15,Sun982
165,24.52,3.48,Male,No,Sun,Dinner,3,8.17,Jacob Hansen,4.031120e+12,Sun9043
75,10.51,1.25,Male,No,Sat,Dinner,2,5.26,Kenneth Hayes,2.131420e+14,Sat5056
110,14.00,3.00,Male,No,Sat,Dinner,2,7.00,James Sanchez,3.452430e+14,Sat6801
189,23.10,4.00,Male,Yes,Sun,Dinner,3,7.70,Richard Stevens,3.560190e+15,Sun1821
209,12.76,2.23,Female,Yes,Sat,Dinner,2,6.38,Sarah Cunningham,3.418770e+14,Sat1274

In [ ]:
#nlargest and nsmalest

df.nlargest(10,'tip')

,total_bill,tip,gender,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
170,50.81,10.00,Male,Yes,Sat,Dinner,3,16.94,Gregory Clark,5.473850e+15,Sat1954
212,48.33,9.00,Male,No,Sat,Dinner,4,12.08,Alex Williamson,6.762190e+11,Sat4590
23,39.42,7.58,Male,No,Sat,Dinner,4,9.86,Lance Peterson,3.542580e+15,Sat239
59,48.27,6.73,Male,No,Sat,Dinner,4,12.07,Brian Ortiz,6.596450e+15,Sat8139
141,34.30,6.70,Male,No,Thur,Lunch,6,5.72,Steven Carlson,3.526520e+15,Thur1025
183,23.17,6.50,Male,Yes,Sun,Dinner,4,5.79,Dr. Michael James,4.718500e+12,Sun6059
214,28.17,6.50,Female,Yes,Sat,Dinner,3,9.39,Marissa Jackson,4.922300e+15,Sat3374
47,32.40,6.00,Male,No,Sun,Dinner,4,8.10,James Barnes,3.552000e+15,Sun9677
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5.296070e+15,Sat2657
88,24.71,5.85,Male,No,Thur,Lunch,2,12.36,Roger Taylor,4.410250e+12,Thur9003

In [ ]:
df.nsmallest(10,'tip')

,total_bill,tip,gender,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
67,3.07,1.00,Female,Yes,Sat,Dinner,1,3.07,Tiffany Brock,4.359490e+15,Sat3455
92,5.75,1.00,Female,Yes,Fri,Dinner,2,2.88,Leah Ramirez,3.508910e+15,Fri3780
111,7.25,1.00,Female,No,Sat,Dinner,1,7.25,Terri Jones,3.559220e+15,Sat4801
236,12.60,1.00,Male,Yes,Sat,Dinner,2,6.30,Matthew Myers,3.543680e+15,Sat5032
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3.560330e+15,Sun2959
215,12.90,1.10,Female,Yes,Sat,Dinner,2,6.45,Jessica Owen,4.726900e+12,Sat6983
237,32.83,1.17,Male,Yes,Sat,Dinner,2,16.42,Thomas Brown,4.284720e+15,Sat2929
75,10.51,1.25,Male,No,Sat,Dinner,2,5.26,Kenneth Hayes,2.131420e+14,Sat5056
135,8.51,1.25,Female,No,Thur,Lunch,2,4.26,Rebecca Harris,4.320270e+15,Thur6600
235,10.07,1.25,Male,No,Sat,Dinner,2,5.04,Sean Gonzalez,3.534020e+15,Sat4615

In [ ]:
#groupby functionality


# 1.splitting
df_grouped = df.groupby('gender')

#Note that the output will not have any visible impact,  except a mention of grouping
df_grouped

In [ ]:
# 2.Applying
# Calculate the mean tip for each gender

mean_tip_by_gender = df_grouped['tip'].mean()
mean_tip_by_gender

gender
Female    2.833448
Male      3.089618
Name: tip, dtype: float64

In [ ]:
df_grouped['tip'].mean()

gender
Female    2.833448
Male      3.089618
Name: tip, dtype: float64

In [ ]:
df_grouped['tip'].max()

gender
Female     6.5
Male      10.0
Name: tip, dtype: float64

In [ ]:
df_grouped['tip'].min()

gender
Female    1.0
Male      1.0
Name: tip, dtype: float64

In [ ]:
df_grouped['tip'].std()

gender
Female    1.159495
Male      1.489102
Name: tip, dtype: float64

In [ ]:
df_grouped['tip'].var()

gender
Female    1.344428
Male      2.217424
Name: tip, dtype: float64

In [ ]:
df_grouped['tip'].count()

gender
Female     87
Male      157
Name: tip, dtype: int64

In [ ]:
df_grouped['tip'].sum()

gender
Female    246.51
Male      485.07
Name: tip, dtype: float64

In [ ]:
#Creating groups on multiple columns

df_grouped = df.groupby(['gender','day'])
df_grouped['tip'].mean()

gender  day
Female  Fri     2.781111
        Sat     2.801786
        Sun     3.367222
        Thur    2.575625
Male    Fri     2.693000
        Sat     3.083898
        Sun     3.220345
        Thur    2.980333
Name: tip, dtype: float64

In [ ]:
## Agg Function

#apply multiple aggregation function to different columns when grouping data
#calculate both the mean and sum of the 'tip' column for each combination of 'Gender' and 'day'

#Group the dataframe by both 'gender' and 'day' and calculate the mean and yhe sum of 'tip' for each combination

df_grouped = df.groupby(['gender','day']).agg({'tip': ['mean','sum']}).reset_index()
df_grouped

   gender   day       tip
                     mean     sum
0  Female   Fri  2.781111   25.03
1  Female   Sat  2.801786   78.45
2  Female   Sun  3.367222   60.61
3  Female  Thur  2.575625   82.42
4    Male   Fri  2.693000   26.93
5    Male   Sat  3.083898  181.95
6    Male   Sun  3.220345  186.78
7    Male  Thur  2.980333   89.41

In [ ]:
#Rename the columns for clarity

df_grouped.columns = ['gender','day','Average tip','total_tip']
df_grouped

   gender   day  Average tip  total_tip
0  Female   Fri     2.781111      25.03
1  Female   Sat     2.801786      78.45
2  Female   Sun     3.367222      60.61
3  Female  Thur     2.575625      82.42
4    Male   Fri     2.693000      26.93
5    Male   Sat     3.083898     181.95
6    Male   Sun     3.220345     186.78
7    Male  Thur     2.980333      89.41